name: Plastic Funeral Build

env:
  PLUG: Plastic Funeral
  NOSPACE: PlasticFuneral

on:
  push:
    paths:
      - '**Plastic Funeral**'
      - '**PlasticFuneral**'
  pull_request:
    paths:
      - '**Plastic Funeral**'
      - '**PlasticFuneral**'
    branches:
      - master

jobs:
  build:
    name: build
    strategy:
      matrix:
        include:
        - {
            name: "Win64",
            os: windows-latest,
            compiler: "Visual Studio 17 2022",
            folder: "build_windows"
          }
        - {
            name: "Linux",
            os: ubuntu-latest,
            compiler: "Unix Makefiles",
            folder: "build_linux"
          }
#        - {
#            name: "Mac",
#            os: macos-latest,
#            compiler: "Xcode",
#            folder: "build_mac"
#          }
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - if: startsWith(matrix.os, 'ubuntu')
      name: (linux) install juce dependencies
      id: juce_dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install g++ libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev

    - name: cache stuff
      id: cache_stuff
      uses: actions/cache@v3
      with:
        path: "${{env.PLUG}}/source/${{matrix.folder}}"
        key: "${{env.NOSPACE}}_${{matrix.folder}}"

    - if: startsWith(matrix.os, 'windows')
      name: (windows) configure
      id: configure_windows
      run: |
        cd "${{env.PLUG}}/source"
        cmake -DBANNERTYPE=0 -B "${{matrix.folder}}" -G "${{matrix.compiler}}" -T host=x64 -A x64

    - if: ${{ !startsWith(matrix.os, 'windows') }}
      name: (unix) configure
      id: configure_mac
      run: |
        cd "${{env.PLUG}}/source"
        cmake -DBANNERTYPE=0 -B "${{matrix.folder}}" -G "${{matrix.compiler}}"

    - name: build
      id: build
      run: |
        cd "${{env.PLUG}}/source"
        cmake --build "${{matrix.folder}}" --config Release --target ${{env.NOSPACE}}_VST3
        cmake --build "${{matrix.folder}}" --config Release --target ${{env.NOSPACE}}_CLAP

    - if: startsWith(matrix.os, 'windows')
      name: (windows) package
      id: package_windows
      run: |
        mv "Setup/${{matrix.folder}}/paid/${{env.PLUG}}.vst3/Contents/x86_64-win/${{env.PLUG}}.vst3" "Setup/${{env.PLUG}}.vst3"
        rm -r "Setup/${{matrix.folder}}/paid/${{env.PLUG}}.vst3"
        mv "Setup/${{env.PLUG}}.vst3" "Setup/${{matrix.folder}}/paid/${{env.PLUG}}.vst3"
        mv "${{env.PLUG}}/source/${{matrix.folder}}/${{env.NOSPACE}}_artefacts/Release/CLAP/${{env.PLUG}}.clap" "Setup/${{matrix.folder}}/paid/${{env.PLUG}}.clap"

    - if: ${{ !startsWith(matrix.os, 'windows') }}
      name: (unix) package
      id: package
      run: |
        mv "${{env.PLUG}}/source/${{matrix.folder}}/${{env.NOSPACE}}_artefacts/CLAP/${{env.PLUG}}.clap" "Setup/${{matrix.folder}}/paid/${{env.PLUG}}.clap"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{env.PLUG}} ${{ matrix.name }}
        path: Setup/${{matrix.folder}}/paid

    - if: startsWith(matrix.os, 'windows')
      name: (windows) configure free
      id: configure_windows_free
      run: |
        cd "${{env.PLUG}}/source"
        cmake -DBANNERTYPE=1 -B "${{matrix.folder}}" -G "${{matrix.compiler}}" -T host=x64 -A x64

    - if: ${{ !startsWith(matrix.os, 'windows') }}
      name: (unix) configure free
      id: configure_mac_free
      run: |
        cd "${{env.PLUG}}/source"
        cmake -DBANNERTYPE=1 -B "${{matrix.folder}}" -G "${{matrix.compiler}}"

    - name: build free
      id: build_free
      run: |
        cd "${{env.PLUG}}/source"
        cmake --build "${{matrix.folder}}" --config Release --target ${{env.NOSPACE}}_VST3
        cmake --build "${{matrix.folder}}" --config Release --target ${{env.NOSPACE}}_CLAP

    - if: startsWith(matrix.os, 'windows')
      name: (windows) package free
      id: package_windows_free
      run: |
        mv "Setup/${{matrix.folder}}/free/${{env.PLUG}}.vst3/Contents/x86_64-win/${{env.PLUG}}.vst3" "Setup/${{env.PLUG}}.vst3"
        rm -r "Setup/${{matrix.folder}}/free/${{env.PLUG}}.vst3"
        mv "Setup/${{env.PLUG}}.vst3" "Setup/${{matrix.folder}}/free/${{env.PLUG}}.vst3"
        mv "${{env.PLUG}}/source/${{matrix.folder}}/${{env.NOSPACE}}_artefacts/Release/CLAP/${{env.PLUG}}.clap" "Setup/${{matrix.folder}}/free/${{env.PLUG}}.clap"

    - if: ${{ !startsWith(matrix.os, 'windows') }}
      name: (unix) package free
      id: package_free
      run: |
        mv "${{env.PLUG}}/source/${{matrix.folder}}/${{env.NOSPACE}}_artefacts/CLAP/${{env.PLUG}}.clap" "Setup/${{matrix.folder}}/free/${{env.PLUG}}.clap"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{env.PLUG}} Free ${{ matrix.name }}
        path: Setup/${{matrix.folder}}/free

    - if: startsWith(matrix.os, 'windows')
      name: (windows) build installer
      id: installer
      run: |
        cd Setup
        iscc "${{env.PLUG}}.iss"
        iscc "${{env.PLUG}} Free.iss"

    - if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.PLUG}} Installer
        path: "Setup/Output/${{env.PLUG}} Installer.exe"

    - if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.PLUG}} Free Installer
        path: "Setup/Output/${{env.PLUG}} Free Installer.exe"

